### ISSUE TITLE
Mod doesn't work on 0.E

### ISSUE THREAD

**Issue by ProjectileWaterfowl** [Zupercharged/CDDA-Alternate-ear-graphics#2]
Both the mutations and the crafted items seem to be broken as of 0.E-2 and aren't visible when in use.

EDIT: I figured it out. You need to add "UNDEAD_PEOPLE_BASE" to the compatibility list. Nice mod, by the way.

**Comment by Zupercharged** [comment]
Hi, sorry for the late response.

Thank you for reminding me to add compatibility to the new tileset id, but just to let you know; for the latest experimentals this only fixes the ear cosmetics while worn (it does manage to offset the base textures though lol). I asked SDG and apparently its a known issue for mods that replace textures in base tilesets, the cosmetics still work though because they're new items. Basically if updating the compatibilities fixed it for you, don't update to latest experimental because something changed that breaks something else.

https://github.com/CleverRaven/Cataclysm-DDA/issues/45563

Glad you liked the mod though! Have fun with it!
